version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/
      timeout: 300
      runas: root
      commands:
        - chmod +x /opt/codedeploy-agent/deployment-root/$CODEDEPLOY_DEPLOYMENT_ID/deployment-archive/scripts/start_server.sh
        - chmod +x /opt/codedeploy-agent/deployment-root/$CODEDEPLOY_DEPLOYMENT_ID/deployment-archive/scripts/stop_server.sh
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
